group_name_prefix:
  type: string
  default: "board-"

manage_url:
  type: string
  default: "/g/{group}"

group_name_overrides:
  type: list
  list_type: compact
  default: ""

show_for_staff:
  type: bool
  default: true

plugin_outlet:
  type: string
  default: "auto"
